#define TAPPING_TERM 250
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 3000  // 3 seconds.

#define QUICK_TAP_TERM 120
#define FLOW_TAP_TERM 150

#define COMBO_ONLY_FROM_LAYER 0

#define RGB_MATRIX_DEFAULT_HUE 180
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING
