#define EE_HANDS
#define RGBLIGHT_SPLIT

#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 3000  // 3 seconds.
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define QUICK_TAP_TERM 140
#define FLOW_TAP_TERM 150

#define COMBO_STRICT_TIMER
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_MUST_TAP_PER_COMBO

#define RGB_MATRIX_DEFAULT_HUE 120
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS / 3
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_STARLIGHT_SMOOTH
#define RGB_MATRIX_DEFAULT_SPD 10
